name = "dineralflow-api"
main = "src/index.mjs"
compatibility_date = "2026-05-05"
workers_dev = true

[vars]
APP_ENV = "production"
PUBLIC_BASE_URL = "https://dineralflow-api.v-basilcowich.workers.dev"
EXPOSE_DEVELOPMENT_TOKENS = "true"

[observability.logs]
enabled = true

[triggers]
crons = ["0 */6 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "dineralflow"
database_id = "51b3c8bb-8882-4f6f-9dec-36e2ea6cf778"
